### ISSUE TITLE
Show CLI support for Document DB 

### ISSUE THREAD

**Issue by nicolehaugen** [lostintangent/node-e2e-nina2016#14] opened 2017-02-15 15:33 UTC
I found it confusing that the walk-through led me to the Azure portal to create the Document DB - is it because Azure CLI doesn't currently have full support for this part of the scenario?  Note that I did find info on how to do this...I haven't tried it yet, but plan to: https://docs.microsoft.com/en-us/azure/documentdb/documentdb-automation-resource-manager-cli.

If this works, consider updating the walk-through to create Document DB via the CLI since it's always cumbersome to go to the portal.  And, if the purpose is to also show the portal, perhaps just have a blurb pointing them to where they can find their resource group via the portal.

**Comment by lostintangent** [comment] 2017-02-15 16:07
DocDB support only just landed in the CLI recently, and it still has a few bugs (that I filed), which prevent it from being a completely smooth experience. Once those are resolved, I'll update the tutorial.

The intent of this tutorial was to be 100% CLI focused, which is the why #1 and #2 issues on this repo are related to removing the need for portal steps. It was unfortunate that I needed to use the portal at all, but the DocDB support wasn't available in time for the keynote that this demo was given in.

This is a dupe of #1, so I'm going to close this issue, and we can track the DocDB CLI improvement via #1. Thanks!

**Closed as completed by lostintangent** 2017-02-15 16:07 UTC
